name: DEPLOY TO AWS

on:
    push:
        branches: [ dev, main ]
    pull_request:
        types: [closed]
        branches:
            - dev

jobs:
    aws-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 16
            - run: npm install
            - run: npm run bundle
            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@v2.2.1
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                  ARGS: '-rltgoDzvO --delete'
                  SOURCE: 'app/'
                  REMOTE_HOST: "ec2-54-157-248-112.compute-1.amazonaws.com"
                  REMOTE_USER: ubuntu
                  TARGET: 'nodeapps/survey-backend'
            - name: Execute SSH commmands on remote server
              uses: JimCronqvist/action-ssh@master
              env:
                  NAME: 'Root'
              with:
                  hosts: 'ubuntu@ec2-54-157-248-112.compute-1.amazonaws.com'
                  privateKey: ${{ secrets.SERVER_SSH_KEY }}
                  debug: false
                  command: |
                      cd nodeapps/survey-backend
                      npm install
                      sudo systemctl stop survey-backend
                      sudo cp survey-backend.service /lib/systemd/system/survey-backend.service
                      sudo systemctl daemon-reload
                      sudo systemctl start survey-backend
